#!/usr/bin/env python3
"""Generate the index, split by page type.

One index.md read in full on every query works at 64 pages. At a few hundred it
is thousands of words of overhead per question, and at a thousand it does not
work at all. So: a small table of contents, and one file per type that an agent
reads only when it needs that type.

Generated from the pages themselves, so it cannot drift out of date the way a
hand-maintained index silently does.

Each page's one-liner comes from `summary:` in its frontmatter. Where that is
missing it falls back to the first sentence after the heading, which is usually
the definition — good enough, and it means no page has to be rewritten to adopt
this.

Usage:
  index.py            write wiki/index.md and wiki/index-<type>.md
  index.py --check    print what it would write
  index.py --audit    report pages the generator cannot summarise, and
                      people pages that appear in only one source
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
GENERATED = re.compile(r"^index(-[a-z]+)?\.md$")
SKIP = {"log.md", "timeline.md"}

# order matters: this is the order a reader meets them
TYPES = [
    ("project", "index-projects.md", "Projects",
     "Things with status, decisions and open questions."),
    ("concept", "index-concepts.md", "Concepts",
     "The joins. Where two or more projects meet."),
    ("person",  "index-people.md",   "People",
     "Only those who appear in two sources, or who decided something."),
    ("source",  "index-sources.md", "Sources",
     "One per ingested document. See timeline.md for event order."),
    ("query",   "index-queries.md", "Queries",
     "Answers filed back — syntheses worth keeping, from the questions that pulled them out."),
]


def field(text, name):
    m = re.search(rf"^{name}:\s*(.+)$", text, re.M)
    return m.group(1).strip().strip('"').strip("'") if m else None


def summarise(text) -> str:
    s = field(text, "summary")
    if s:
        return s
    body = text.split("---", 2)[2] if text.startswith("---") else text
    lines = [l.strip() for l in body.splitlines()]
    for i, l in enumerate(lines):
        if l.startswith("# "):
            for nxt in lines[i + 1:]:
                if nxt and not nxt.startswith((">", "#", "|", "-", "*", "_")):
                    first = re.split(r"(?<=[.!?])\s", nxt)[0]
                    return first if len(first) < 220 else first[:200].rstrip() + "…"
            break
    return ""


def collect() -> dict:
    out = {t: [] for t, _, _, _ in TYPES}
    out["_other"] = []
    for p in sorted(WIKI.rglob("*.md")):
        if p.name in SKIP or GENERATED.match(p.name):
            continue
        text = p.read_text(errors="replace")
        row = {
            "slug": p.stem,
            "summary": summarise(text),
            "status": field(text, "status"),
            "parent": field(text, "parent"),
            "date": field(text, "source_date"),
            "conf": field(text, "date_confidence"),
        }
        out.setdefault(field(text, "type") or "_other", out["_other"]).append(row) \
            if (field(text, "type") or "_other") in out else out["_other"].append(row)
    return out


def render_type(kind, title, blurb, rows) -> str:
    lines = [f"# {title}", "", blurb, "",
             f"Generated by `scripts/index.py` — do not edit by hand.",
             f"Back to [[index]].", ""]
    if not rows:
        lines += ["_(none yet)_", ""]
        return "\n".join(lines)
    if kind == "source":
        rows = sorted(rows, key=lambda r: (r["date"] or "9999", r["slug"]))
    else:
        rows = sorted(rows, key=lambda r: r["slug"])
    for r in rows:
        bits = []
        if r["status"]:
            bits.append(f"**{r['status']}**")
        if kind == "source" and r["conf"] and r["conf"] != "high":
            bits.append(f"date {r['conf']}")
        tag = f"  ({', '.join(bits)})" if bits else ""
        summary = f" — {r['summary']}" if r["summary"] else ""
        lines.append(f"- [[{r['slug']}]]{summary}{tag}")
    lines.append("")
    return "\n".join(lines)


def render_toc(data) -> str:
    lines = ["# Index", "",
             "The catalog, split by type. Read the one you need — not all of them.",
             "Generated by `scripts/index.py`; do not edit by hand.", "", ]
    for kind, fname, title, blurb in TYPES:
        n = len(data.get(kind, []))
        lines.append(f"- [[{fname[:-3]}]] — **{title}** ({n}). {blurb}")
    lines += ["- [[timeline]] — **Time.** What happened when, versus when it arrived.", ""]
    other = data.get("_other", [])
    if other:
        lines += ["## Not typed", "",
                  "These carry no `type:` in frontmatter, so nothing can file them:", ""]
        lines += [f"- [[{r['slug']}]]" for r in other] + [""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--audit", action="store_true")
    args = ap.parse_args()
    data = collect()

    if args.audit:
        print("Pages with no usable summary (add `summary:` to frontmatter):")
        n = 0
        for kind, rows in data.items():
            for r in rows:
                if not r["summary"]:
                    print(f"  {kind:<10} {r['slug']}"); n += 1
        print(f"  ({n} total)\n")
        print("Person pages appearing in only one source — below the people rule:")
        m = 0
        for r in data.get("person", []):
            if r["slug"].startswith("TEMP_"):
                continue
            pg = next(WIKI.rglob(f"{r['slug']}.md"), None)
            hits = sum(1 for p in WIKI.rglob("*.md")
                       if p != pg and f"[[{r['slug']}]]" in p.read_text(errors="replace")
                       and "sources" in p.parts)
            if hits <= 1:
                print(f"  {r['slug']}  (cited by {hits} source page(s))"); m += 1
        print(f"  ({m} candidates to fold back into their source page)")
        return 0

    files = {"index.md": render_toc(data)}
    for kind, fname, title, blurb in TYPES:
        files[fname] = render_type(kind, title, blurb, data.get(kind, []))

    if args.check:
        for name, body in files.items():
            print(f"\n{'='*8} {name} {'='*8}\n{body}")
        return 0
    for name, body in files.items():
        (WIKI / name).write_text(body)
    print("wrote " + ", ".join(f"wiki/{n}" for n in files))
    return 0


if __name__ == "__main__":
    sys.exit(main())
