#!/usr/bin/env python3
"""Generate wiki/timeline.md -- what happened, in the order it happened.

log.md is ordered by INGEST: when the owner dropped a file. This is ordered by EVENT:
when the thing actually occurred. They are different, often wildly, and reading
the ingest order as a causal story gives you the wrong answer.

The two clocks are printed side by side on purpose, so the divergence is visible
rather than merely true.

Derived from the source pages, so it cannot drift. Regenerate after every ingest.

Usage:
  timeline.py            write wiki/timeline.md
  timeline.py --check    print it without writing
"""

import argparse
import datetime as dt
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCES = ROOT / "wiki" / "sources"
OUT = ROOT / "wiki" / "timeline.md"


def field(text, name):
    m = re.search(rf"^{name}:\s*(.+)$", text, re.M)
    return m.group(1).strip() if m else None


def drop_order() -> dict:
    """True ingest order, from the manifest's append order.

    `ingested:` is a DATE, so everything dropped on one day ties and the
    tiebreak invents an order. The manifest is append-only, so its line order is
    the real sequence -- it is the ingest log, and it already exists.
    """
    mf = ROOT / ".state" / "manifest.jsonl"
    order = {}
    if not mf.exists():
        return order
    for i, line in enumerate(l for l in mf.read_text().splitlines() if l.strip()):
        try:
            raw = json.loads(line)["raw_path"]
        except Exception:
            continue
        order[pathlib.Path(raw).stem] = i
    return order


def collect():
    rows = []
    for p in sorted(SOURCES.glob("*.md")):
        t = p.read_text()
        sd = field(t, "source_date")
        if not sd:
            continue
        title = next((l[2:].strip() for l in t.splitlines() if l.startswith("# ")), p.stem)
        rows.append({
            "slug": p.stem,
            "title": title,
            "event": sd,
            "ingested": field(t, "ingested") or "?",
            "conf": field(t, "date_confidence") or "?",
            "how": field(t, "date_from") or "?",
            "kind": field(t, "kind") or "",
            "source_file": field(t, "source_file") or "",
        })
    return rows


def render(rows) -> str:
    if not rows:
        return "# Timeline\n\n_(no dated sources yet)_\n"
    by_event = sorted(rows, key=lambda r: r["event"])
    manifest = drop_order()
    # match a source page to its raw file via source_file, else by stem
    def seq(r):
        for key, i in manifest.items():
            if key in r["slug"] or r["slug"] in key or key in r.get("source_file", ""):
                return i
        return 10**6
    ranked = sorted(rows, key=lambda r: (seq(r), r["slug"]))
    order_ingest = {r["slug"]: i for i, r in enumerate(ranked)}

    out = ["# Timeline", "",
           "What happened, in the order it happened. Generated by",
           "`scripts/timeline.py` from the source pages — do not edit by hand.", "",
           "`log.md` is ordered by when a file was **dropped**. This is ordered by",
           "when the thing **occurred**. Where the two columns disagree, the wiki",
           "learned things out of order.", "",
           "| # | Event date | Source | How dated | Drop order |",
           "|---|---|---|---|---|"]
    flagged = []
    for i, r in enumerate(by_event, 1):
        drop = order_ingest[r["slug"]] + 1
        mark = " ⟲" if drop != i else ""
        conf = "" if r["conf"] == "high" else f" ({r['conf']})"
        out.append(f"| {i} | {r['event']} | [[{r['slug']}]] — {r['title']} | "
                   f"{r['how']}{conf} | {drop}{mark} |")
        if r["conf"] in ("low", "medium"):
            flagged.append(r)

    out += ["", f"**⟲ marks a source learned out of order.** "
                f"{sum(1 for i, r in enumerate(by_event, 1) if order_ingest[r['slug']]+1 != i)}"
                f" of {len(by_event)} arrived out of sequence.", ""]
    if flagged:
        out += ["## Dates worth checking", "",
                "These were not confirmed by two agreeing signals:", ""]
        for r in flagged:
            out.append(f"- [[{r['slug']}]] — {r['event']}, from {r['how']}, "
                       f"confidence **{r['conf']}**")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render(collect())
    if args.check:
        print(text)
    else:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
